//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cvm.Web.AdminPages {
    
    
    public partial class EditAssignmentsSearch {
        
        /// <summary>
        /// SearchCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cvm.Web.AdminPages.CommonCtrl.SearchCvCtrl SearchCtrl;
    }
}
