//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cvm.Web.AdminPages {
    
    
    public partial class EditAssignmentResources {
        
        /// <summary>
        /// ListFilterCtrl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cvm.Web.AdminPages.CommonCtrl.ListFilterCtrl ListFilterCtrl1;
        
        /// <summary>
        /// TabularCtrl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cvm.Web.AdminPages.CommonCtrl.TabularCtrl TabularCtrl1;
        
        /// <summary>
        /// ResourceGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AdmControl.AdmGridView ResourceGrid;
        
        /// <summary>
        /// KeywordTextBox control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox KeywordTextBox;
        
        /// <summary>
        /// SearchGrid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AdmControl.AdmGridView SearchGrid;
        
        /// <summary>
        /// AuxCtrl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Cvm.Web.AdminPages.CommonCtrl.EditAssignmentsAuxCtrl AuxCtrl2;
    }
}
