//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cvm.Web.Public {
    
    
    public partial class CompanySignup {
        
        /// <summary>
        /// MainPanel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel MainPanel;
        
        /// <summary>
        /// CCUserData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AdmControl.ContainerCtrl CCUserData;
        
        /// <summary>
        /// UserObjCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AutoForm.AutoForm1 UserObjCtrl;
        
        /// <summary>
        /// ATBPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AdmControl.AdmTextBox ATBPassword;
        
        /// <summary>
        /// ATBReEnterPassword control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AdmControl.AdmTextBox ATBReEnterPassword;
        
        /// <summary>
        /// CCCompanyData control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AdmControl.ContainerCtrl CCCompanyData;
        
        /// <summary>
        /// CompanyInfoCtrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AutoForm.AutoForm1 CompanyInfoCtrl;
        
        /// <summary>
        /// ABCreateCompany control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Napp.Web.AdmControl.AdmButton ABCreateCompany;
    }
}
